= Yang Shuqi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: SaveIt

---

== Overview

This document is written for summarizing my contributions in the project SaveIt.

== Summary of contributions
SaveIt is a platform for you to keep track of issues that you encounter and the corresponding solutions that you found on through your search engine.
More importantly, SaveIt is ​optimized for those who prefer to work with a Command Line Interface​ (CLI) while still having the benefits of a Graphical User Interface (GUI).

* *Major enhancements*:
** Improved *Edit* Command feature
*** What it does: It allows a user to edit any fields in the issue and solution.
*** Justification: The current data structure is an issue is bound to multiple solutions. Since a solution includes a solution link and a solution remark, users should be able to edit any field in a solution instead of replacing the whole solution.
*** Highlights: It requires a depth analysis for different conditions whether the command is valid. Also, we need to tell the user if he is in the wrong directory. It improves the efficiency to edit their issues and solutions.

** Implemented *Add Tags*
*** What it does: It allows the user to add tags to specified issues.
*** Justification: This feature allows users to add tags to an issue if they forgot to add tags when they create an issue. It is troublesome to replace all the issues when using `edit` command.
*** Highlights: It requires a depth analysis to decide whether the command should be accepted. It is flexible to users as they can provide a range of indexes or some discrete indexes to add tags in one execution.

* *Minor enhancements*:
** Implemented `refactortag` command: Allows users to rename or remove a specific tag for all entries with that tag.
** Implemented `command highlight` feature: Allows users to differentiate their inputs by highlight command word,  parameters and values in different colors.
** Implemented `command alias` feature: Allows users to type command words less but achieving the same functionality.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
** Community:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

