= Yang Shuqi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

= PROJECT: SaveIt

---

== Overview

This document is written for summarizing my contributions in the project SaveIt.

SaveIt is geared at keeping track of the issues and solutions that the user finds online.
It is designed for programmers who are used to Command Line Interface​ (CLI) applications and are good at typing while still having the benefits of a Graphical User Interface (GUI).

SaveIt​ is implemented for applying CS2103 learning outcomes and show understanding of the software design.
It is implemented by a group of CS2103 students, including myself. My key contribution is *sort command*.

SaveIt is written in Java and JavaFX, and is morphed from AddressBook-level4, the application used for teaching Software Engineering principles.

== Summary of contributions

* *Major enhancement*: added *the ability to sort issue list*
** What it does: It allows the user to sort issues shown in the list.
** Justification: This feature improves the product significantly because it helps the user to view the issues in the order that they want, so that they can organize the record of issues better.
** Highlights: This command changes the way how issues are listed in the application. It needs effort to combine sorting and filtering together properly and make sure the correct issue can be retrieved from the sorted list.

* *Minor enhancement*:
** Added the ability to set and reset primary solution. https://github.com/CS2103-AY1819S1-T12-4/main/pull/177[#177]
** Added a confirmation check for clear command. https://github.com/CS2103-AY1819S1-T12-4/main/pull/116[#116]
** Implement UI for SortType. https://github.com/CS2103-AY1819S1-T12-4/main/pull/208[#208]
** Improve backend storage of Issue (added createdTime, lastModifiedTime). https://github.com/CS2103-AY1819S1-T12-4/main/pull/108/files#diff-f1fa68a447dd90e93ca8a91b132a026a[#108],
https://github.com/CS2103-AY1819S1-T12-4/main/pull/208/files#diff-f1fa68a447dd90e93ca8a91b132a026a[#208]
** Improve solution structure. https://github.com/CS2103-AY1819S1-T12-4/main/pull/180[#180]

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=yshu7[Functional code]]

* *Other contributions*:

** Project management:
*** Managed milestones and checked issue status on GitHub
** Enhancements to existing features:
*** Updated tests to fit mid-v1.2 features (Pull requests https://github.com/CS2103-AY1819S1-T12-4/main/pull/52[#52])
** Documentation:
*** Update About Us Page: https://github.com/CS2103-AY1819S1-T12-4/main/pull/2[#2]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-T12-4/main/pull/25[#25],
https://github.com/CS2103-AY1819S1-T12-4/main/pull/32[#32], https://github.com/CS2103-AY1819S1-T12-4/main/pull/77[#77],
https://github.com/CS2103-AY1819S1-T12-4/main/pull/123[#123], https://github.com/CS2103-AY1819S1-T12-4/main/pull/168[#168],
https://github.com/CS2103-AY1819S1-T12-4/main/pull/169[#169], https://github.com/CS2103-AY1819S1-T12-4/main/pull/178[#178],

*** Reported bugs and suggestions for other team members in the group:  https://github.com/CS2103-AY1819S1-T12-4/main/issues/111[111], https://github.com/CS2103-AY1819S1-T12-4/main/issues/115[115],
https://github.com/CS2103-AY1819S1-T12-4/main/issues/203[203], https://github.com/CS2103-AY1819S1-T12-4/main/issues/210[210], https://github.com/CS2103-AY1819S1-T12-4/main/issues/236[236],
https://github.com/CS2103-AY1819S1-T12-4/main/issues/237[237]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=clear]

include::../UserGuide.adoc[tag=setprimary]

include::../UserGuide.adoc[tag=resetprimary]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=confirmation]

include::../DeveloperGuide.adoc[tag=setprimary]

include::../DeveloperGuide.adoc[tag=resetprimary]
